name: braw3
description: Simple flashcard prototype with audio (and optional video)
version: 1.0.0+2
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  video_player: ^2.8.6
  shared_preferences: ^2.3.2
  file_picker: ^10.3.2
  path_provider: ^2.1.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/cards.json
    - assets/audio/
    - assets/audio/scottish/
    - assets/audio/context/
    - assets/images/
    - assets/video/
    - assets/i18n/

  fonts:
    - family: EBGaramond
      fonts:
        - asset: assets/fonts/EBGaramond/EBGaramond-Regular.ttf
        - asset: assets/fonts/EBGaramond/EBGaramond-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/EBGaramond/EBGaramond-Bold.ttf
          weight: 700
        - asset: assets/fonts/EBGaramond/EBGaramond-Italic.ttf
          style: italic

    - family: CharisSIL
      fonts:
        - asset: assets/fonts/CharisSIL/CharisSIL-Regular.ttf
        - asset: assets/fonts/CharisSIL/CharisSIL-Bold.ttf
          weight: 700
        - asset: assets/fonts/CharisSIL/CharisSIL-Italic.ttf
          style: italic

    - family: SourceSerif4
      fonts:
        - asset: assets/fonts/SourceSerif4/SourceSerif4-Regular.ttf
